
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Update as needed
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 